from .custom_types import FinalStateResult

states_dict: dict[int, dict[str, int | FinalStateResult]] = {
    0: {
        "ws": 0,
        "EndOfLine": 0,
        "Letter": 4,
        "Digit": 6,
        "dot": 30,
        "/": 1,
        "=": 11,
        "!": 13,
        "<": 17,
        ">": 18,
        "*": 24,
        "+": 8,
        "-": 23,
        '"': 28,
        "(": 27,
        ")": 27,
        "{": 27,
        "}": 27,
        ",": 27,
        ";": 27,
        ":": 27,
        "other": 101,
    },
    1: {"/": 2, "other": 3},
    2: {"EndOfLine": 0, "other": 2},
    3: FinalStateResult("div_op", put_back=True),
    4: {"Letter": 4, "Digit": 4, "_": 4, "other": 5},
    5: FinalStateResult("id", put_back=True),
    6: {"Digit": 6, "dot": 9, "other": 7},
    7: FinalStateResult("intnum", put_back=True),
    8: FinalStateResult("add_op"),
    9: {"Digit": 9, "other": 10},
    10: FinalStateResult("realnum", put_back=True),
    11: {"=": 12, "other": 14},
    12: FinalStateResult("equal_op"),
    13: {"=": 16, "other": 15},
    14: FinalStateResult("assign_op", put_back=True),
    15: FinalStateResult("not_op", put_back=True),
    16: FinalStateResult("not_equal_op"),
    17: {"=": 22, "other": 21},
    18: {"=": 20, "other": 19},
    19: FinalStateResult("greater_op", put_back=True),
    20: FinalStateResult("greater_equal_op"),
    21: FinalStateResult("less_op", put_back=True),
    22: FinalStateResult("less_equal_op"),
    23: FinalStateResult("sub_op"),
    24: {"*": 26, "other": 25},
    25: FinalStateResult("mul_op", put_back=True),
    26: FinalStateResult("pow_op"),
    27: FinalStateResult("punct"),
    28: {'"': 29, "other": 28},
    29: FinalStateResult("stringlit"),
    30: {"Digit": 9, "other": 102},
    101: FinalStateResult("error", error=101),
    102: FinalStateResult("error", error=102),
}
